/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;
import java.awt.HeadlessException;
import java.util.regex.Pattern;  
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author CARLOSANTONIOLOPEZAMAZTALLI
 */
public final class Ventanaprincipal extends javax.swing.JFrame {
    public static LinkedList contenedor=new LinkedList();
    public int buscar;
    /**
     * Creates new form Ventanaprincipal
     */
    String textoArchivo;
    int indiceActual;
    int totalPersonas;
    
    public Ventanaprincipal()  {
        initComponents();
        this.setTitle("Farmacia");
     
       // mostrarDatos();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoproveedor = new javax.swing.ButtonGroup();
        grupoSucursal = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        cantProductoTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        borrar = new javax.swing.JButton();
        GuardarButton = new javax.swing.JButton();
        jtipobox = new javax.swing.JComboBox<>();
        jNombreButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSucursalBox = new javax.swing.JCheckBox();
        jNombreButton2 = new javax.swing.JRadioButton();
        jNombreButton3 = new javax.swing.JRadioButton();
        jNombreButton4 = new javax.swing.JRadioButton();
        jNombreButton5 = new javax.swing.JRadioButton();
        jSucursalBox2 = new javax.swing.JCheckBox();
        jSucursalBox3 = new javax.swing.JCheckBox();
        jSucursalBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nombre del producto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("tipo del producto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Sucursal:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cantidad del producto:");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        cantProductoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantProductoTextFieldActionPerformed(evt);
            }
        });
        cantProductoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantProductoTextFieldKeyTyped(evt);
            }
        });

        borrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        GuardarButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GuardarButton.setText("Guardar");
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(borrar)
                .addGap(121, 121, 121)
                .addComponent(GuardarButton)
                .addContainerGap(986, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(GuardarButton))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jtipobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cubrebocas", "Medicamento", "analgesicos", "pastillas", "Inyecciones", "Cepillo de dientes", "Botiquin" }));
        jtipobox.setSelectedIndex(-1);
        jtipobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtipoboxActionPerformed(evt);
            }
        });

        grupoproveedor.add(jNombreButton);
        jNombreButton.setText("Tomas Castro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Nombre del proveedor:");

        grupoSucursal.add(jSucursalBox);
        jSucursalBox.setText("villa laredo");

        grupoproveedor.add(jNombreButton2);
        jNombreButton2.setText("ramon hernandez");
        jNombreButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreButton2ActionPerformed(evt);
            }
        });

        grupoproveedor.add(jNombreButton3);
        jNombreButton3.setText("Jose fernandez");
        jNombreButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreButton3ActionPerformed(evt);
            }
        });

        grupoproveedor.add(jNombreButton4);
        jNombreButton4.setText("luis donaldo");

        grupoproveedor.add(jNombreButton5);
        jNombreButton5.setText("hector valdilla");

        grupoSucursal.add(jSucursalBox2);
        jSucursalBox2.setText("coatzacoalcos");

        grupoSucursal.add(jSucursalBox3);
        jSucursalBox3.setText("san martin");
        jSucursalBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSucursalBox3ActionPerformed(evt);
            }
        });

        grupoSucursal.add(jSucursalBox4);
        jSucursalBox4.setText("Santa Isabel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jSucursalBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSucursalBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSucursalBox3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSucursalBox4)
                                        .addGap(93, 93, 93))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jNombreButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jNombreButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jNombreButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jNombreButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jNombreButton5))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantProductoTextField)
                                    .addComponent(jtipobox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtipobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(cantProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreButton)
                    .addComponent(jNombreButton2)
                    .addComponent(jNombreButton3)
                    .addComponent(jNombreButton4)
                    .addComponent(jNombreButton5)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSucursalBox)
                    .addComponent(jSucursalBox2)
                    .addComponent(jSucursalBox3)
                    .addComponent(jSucursalBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    @SuppressWarnings("null")
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(this, "¿Esta seguro de borrar los datos introducidos?");
        if(respuesta==JOptionPane.YES_OPTION){
           
        try {
               
            nombreTextField.setText("");
            jtipobox.setSelectedIndex(-1);
            cantProductoTextField.setText("");
            jNombreButton.setSelected(false);
            jSucursalBox.setSelected(false);
            grupoproveedor.clearSelection();
            grupoSucursal.clearSelection();
        } catch (Exception ex) {
            Logger.getLogger(Ventanaprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
           JOptionPane.showMessageDialog(this, "Operacion exitosa");
        }        
        
    }//GEN-LAST:event_borrarActionPerformed
   
    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
                  String nombredelproducto= nombreTextField.getText();
                  String tipodelproducto= jtipobox.getSelectedItem().toString();
                  String Cantidaddelproducto=cantProductoTextField.getText();
                  String nombredelproveedor=jNombreButton.getText();
                  String Sucursal=jSucursalBox.getText();
        
            
               boolean alfa = Pattern.matches("^[a-zA-Z]*$", nombredelproducto);
             
               if(alfa=true){
                try{
                 if(nombredelproducto.isEmpty()){
                        JOptionPane.showMessageDialog(this,"Por favor ingrese un nombre de producto, Mensaje de error al Ingresar dato");
                }else {
                        if(tipodelproducto.isEmpty()){
                     JOptionPane.showMessageDialog(this,"Por favor ingrese un tipo de producto, Mensaje de error al Ingresar dato");
           }else{
                    if(Cantidaddelproducto.isEmpty()){
                         JOptionPane.showMessageDialog(this,"Por favor ingrese una cantidad del producto, Mensaje de error al Ingresar dato");
                    }else {
                            
                                if(jNombreButton.isSelected() || jNombreButton2.isSelected() || jNombreButton3.isSelected() || jNombreButton4.isSelected() ||jNombreButton5.isSelected()){
                                    
                                        if(jSucursalBox.isSelected() || jSucursalBox2.isSelected() || jSucursalBox3.isSelected()|| jSucursalBox4.isSelected()){
                                            
                                                        JOptionPane.showMessageDialog(this,"Todos los datos fueron guardados correctamente :), A continuacion se le mostrara un resumen de su pedido");
                                                        Producto claseproducto=new Producto(nombredelproducto,tipodelproducto,Cantidaddelproducto,nombredelproveedor,Sucursal);
                                                        contenedor.add(claseproducto); 
                                                        frmDatos mostrar=new frmDatos();
                                                        mostrar.setVisible(true);
                                                    }else{
                                                            JOptionPane.showMessageDialog(this,"Por favor ingrese una sucursal, Mensaje de error al Ingresar dato");
                                                            } 
                                                                }else{
                                                                         JOptionPane.showMessageDialog(this,"Por favor ingrese un nombre del proveedor, Mensaje de error al Ingresar dato");
                                                                    }
                                                          } 
                                                                         
                                                        }
                        
                                                    } 
       }catch(HeadlessException e){
                System.out.println("Error en el sistema atrapado");
            }
        
         } 
              
               
    }//GEN-LAST:event_GuardarButtonActionPerformed
    
 /*  
    */
    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed
    
    private void jtipoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtipoboxActionPerformed
        String []productos= {"","Cubrebocas","Medicamento","analgesicos","pastillas","inyecciones","Cepillos de diente","Botiquín"};
        JComboBox listaDesplegable= new JComboBox();
        listaDesplegable.setBounds(20,20,100,30);
        
                
    }//GEN-LAST:event_jtipoboxActionPerformed

    private void jNombreButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreButton2ActionPerformed

    private void jNombreButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreButton3ActionPerformed

    private void jSucursalBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSucursalBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSucursalBox3ActionPerformed

    private void cantProductoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantProductoTextFieldKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Solo numeros ingresar ");
        }else{
            JOptionPane.showMessageDialog(this, "Se guardo la cantidad ");
                   //frmDatos mostrar=new frmDatos();
                    //mostrar.setVisible(true);
        }
    }//GEN-LAST:event_cantProductoTextFieldKeyTyped

    private void cantProductoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantProductoTextFieldActionPerformed
      
    }//GEN-LAST:event_cantProductoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarButton;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField cantProductoTextField;
    private javax.swing.ButtonGroup grupoSucursal;
    private javax.swing.ButtonGroup grupoproveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jNombreButton;
    private javax.swing.JRadioButton jNombreButton2;
    private javax.swing.JRadioButton jNombreButton3;
    private javax.swing.JRadioButton jNombreButton4;
    private javax.swing.JRadioButton jNombreButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jSucursalBox;
    private javax.swing.JCheckBox jSucursalBox2;
    private javax.swing.JCheckBox jSucursalBox3;
    private javax.swing.JCheckBox jSucursalBox4;
    private javax.swing.JComboBox<String> jtipobox;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new Ventanaprincipal().setVisible(true);
        }
    }
}
